import { Button, VerticalBox, HorizontalBox, Slider } from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property <bool> playing: false;
    in-out property <float> volmax: 100.0;
    in-out property <float> current_vol: 100.0;
    in-out property <float> current_pos;
    in-out property <float> current_max;
    in-out property <string> current_pos_text: "";
    in-out property <string> current_max_text: "";
    in-out property <string> current_vol_text: "100";
    
    callback play_music();
    callback seek_track(float);
    callback seek_vol(float);
    VerticalBox {
        playpause := Button {
            text: "Play Music";
            clicked => {
                play_music()
            }
        }
        seekbar := HorizontalLayout{
            Text{
                text <=> current_pos_text;
            }
            Slider{
                value <=> current_pos;
                maximum <=> current_max;
                released(pos) =>{
                    seek_track(pos);
                }
            }
            Text{
                text <=> current_max_text;
            }
        }
        HorizontalLayout {
            volbar := Slider{
                value <=> current_vol;
                maximum: volmax;
                changed(pos) =>{
                    seek_vol(pos)
                }
            }
            Text{
                text <=> current_vol_text;
            }
        }
    }
}
